# Generated by Django 5.0.2 on 2024-03-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinateapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='date',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='location',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='time',
        ),
        migrations.AddField(
            model_name='vaccine',
            name='interval',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='quantity_of_doses',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='status',
            field=models.CharField(default='mandatory', max_length=100),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
