# Generated by Django 5.0.2 on 2024-03-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinateapp', '0002_remove_vaccine_capacity_remove_vaccine_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='period',
            field=models.CharField(choices=[('MO', 'month'), ('YR', 'year'), ('DT', 'date')], default='MO', max_length=2),
        ),
    ]
