# Generated by Django 5.0.2 on 2024-04-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinateapp', '0004_alter_vaccine_period_uservaccine'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservaccine',
            name='all_dates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
