# Generated by Django 5.0.2 on 2024-04-06 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinateapp', '0005_uservaccine_all_dates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uservaccine',
            old_name='next_date',
            new_name='fist_date',
        ),
        migrations.RemoveField(
            model_name='uservaccine',
            name='date',
        ),
    ]
