# Generated by Django 5.0.2 on 2024-04-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinateapp', '0009_alter_vaccine_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='status',
        ),
        migrations.AddField(
            model_name='vaccine',
            name='obligation',
            field=models.CharField(choices=[('mandatory', 'mandatory'), ('recomended', 'recomended'), ('non_mandatory', 'non_mandatory')], default='mandatory', max_length=20),
        ),
        migrations.AlterField(
            model_name='uservaccine',
            name='status',
            field=models.CharField(choices=[('done', 'done'), ('pending', 'pending'), ('cancelled', 'cancelled')], default='pending', max_length=10),
        ),
    ]
