# Generated by Django 5.0.2 on 2024-04-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinateapp', '0010_remove_vaccine_status_vaccine_obligation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='obligation',
            field=models.CharField(choices=[('mandatory', 'mandatory'), ('recommended', 'recommended'), ('non_mandatory', 'non_mandatory')], default='mandatory', max_length=20),
        ),
    ]
