version: "3"

services:
  django:
    build: .
    command: sh -c "python manage.py migrate && gunicorn VaccinNate.wsgi --bind 0.0.0.0:$PORT"
    ports:
      - "80:80"
    depends_on:
      - celery

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
